trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm cache clean --force
    rm -rf node_modules
    rm package-lock.json
    npm install
    npm run build
  displayName: 'npm cache clean, delete node_modules, delete package-lock.json, npm install, npm run build'
