parameters:
- name: environment
  displayName: Environment
  type: string
  default: dev
  values:
  - dev
  - test

variables:
  - name: WebAppName
    value: 'pet-testing'
  - name: HOST
    value: '0.0.0.0'
  - name: PORT
    value: '4002'

name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main
jobs:
- job: Job_1
  displayName: Agent Nipts-Pts-Checker-Web-Ui
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - script: |
      if [ "$(parameters.environment)" == "test" ]; then
        echo "##vso[task.setvariable variable=WebAppName;]pet-testing-test"
        echo "##vso[task.setvariable variable=HOST;]0.0.0.0"
        echo "##vso[task.setvariable variable=PORT;]4002"
      fi
  - task: AzureCLI@2
    displayName: Set environment variables in App Service configuration
    inputs:
      azureSubscription: 'AZD-TRD-DEV1'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az webapp config appsettings set --name $(WebAppName) --resource-group DEVPTSINFRG1001 --settings HOST=$(HOST) PORT=$(PORT)
  - task: CmdLine@2
    displayName: install libimagequant-dev
    inputs:
      script: sudo apt install libimagequant-dev
  - task: CmdLine@2
    displayName: npm install pngquant-bin
    inputs:
      script: npm install pngquant-bin
  - task: Npm@1
    displayName: npm install
    inputs:
      verbose: false
  - task: CmdLine@2
    displayName: npm run build
    inputs:
      script: npm run build
  - task: ArchiveFiles@2
    displayName: Archive $(System.DefaultWorkingDirectory)
    inputs:
      rootFolderOrFile: $(System.DefaultWorkingDirectory)
      includeRootFolder: false
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
  - task: DownloadPipelineArtifact@2
    displayName: Download Pipeline Artifact
    inputs:
      artifact: drop
      path: $(System.DefaultWorkingDirectory)
  - task: AzureRmWebAppDeployment@4
    displayName: 'Azure App Service Deploy: $(WebAppName)'
    inputs:
      ConnectedServiceName: 90b91b91-6095-410c-8366-7abd492817d0
      WebAppKind: webAppLinux
      WebAppName: $(WebAppName)
      RuntimeStack: NODE|18-lts
      StartupCommand: npm run start
...