trigger:
  - main

pr: none

variables:
  # Service connection as configured in project settings
  devConnection: "AZD-TRD-DEV1"

  # App name
  devApp: "pet-testing"

stages:
  - stage: build
    displayName: "Build"
    jobs:
      - job: build_test
        displayName: "Build and test"
        pool:
          vmImage: "Ubuntu-lastest"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "10.x"
            displayName: "Install Node.js"
          - script: |
              npm install
              npm run build
              npm run test
            displayName: "npm install, build, and test"
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
              includeRootFolder: false
          - task: PublishPipelineArtifact@0
            inputs:
              targetPath: "$(System.ArtifactsDirectory)"

  - stage: dev
    displayName: "dev"
    dependsOn: build
    jobs:
      - deployment: deploydev
        displayName: "Deploy dev"
        environment: DEV
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPipelineArtifact@1
                  inputs:
                    downloadPath: "$(System.DefaultWorkingDirectory)"
                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: $(devConnection)
                    appType: "webAppLinux"
                    appName: $(devApp)
                    runtimeStack: "NODE|18.0"
                    startUpCommand: "npm run start"
