name: 'V1-B$(Date:yyyyMMdd)-$(BuildID)'

parameters:
  - name: forceDevDeploy
    displayName: "Deploy to DEV?"
    type: boolean
    default: false
  - name: deployToSecondary
    displayName: "Select Secondary Region"
    type: string
    default: None
    values:
      - None
      - DEV
      - TST
      - SND
      - PRE
      - PRD

resources:
  repositories:
    - repository: PipelineCommon
      name: DEFRA-TRD/Defra.TRD.Pipeline.Common
      type: git
      ref: master

variables:
  APIName: DEFRA_nipts-pts-checker-web-ui

extends:
  template: /templates/basic-npm-webapp-deploy-pipeline.yaml@PipelineCommon
  parameters:
    forceDevDeploy: ${{ parameters.forceDevDeploy }}
    deployToSecondary: ${{ parameters.deployToSecondary}}
    appProject: PTS
    appInstanceNumber: $(nc-region-id)04
    appName: DEFRA_nipts-pts-checker-web-ui
    appSettingsEnv: 
      dev: >-
        -PORT "8080"
        -HOST "0.0.0.0"
        -BASE_API_URL "https://$(environment)pts$(nc-function-web-lower)$(nc-resource-webapp-lower)1003.azurewebsites.net"
      tst: >-
        -PORT "8080"
        -HOST "0.0.0.0"
        -BASE_API_URL "https://$(environment)pts$(nc-function-web-lower)$(nc-resource-webapp-lower)1003.azurewebsites.net"
      snd: >-
        -PORT "8080"
        -HOST "0.0.0.0"
        -BASE_API_URL "https://$(environment)pts$(nc-function-web-lower)$(nc-resource-webapp-lower)1003.azurewebsites.net"
      pre: >-
        -PORT "8080"
        -HOST "0.0.0.0"
        -BASE_API_URL "https://$(environment)pts$(nc-function-web-lower)$(nc-resource-webapp-lower)1003.azurewebsites.net"
      prd: >-
        -PORT "8080"
        -HOST "0.0.0.0"
        -BASE_API_URL "https://$(environment)pts$(nc-function-web-lower)$(nc-resource-webapp-lower)1003.azurewebsites.net"
    runSonarScan: true
    #runVulnerabilityScan: true
    #skipOwaspScan: false
