name: 'V1-B$(Date:yyyyMMdd)-$(BuildID)'

parameters:
  - name: forceDevDeploy
    displayName: "Deploy to DEV?"
    type: boolean
    default: false
  - name: deployToSecondary
    displayName: "Select Secondary Region"
    type: string
    default: None
    values:
      - None
      - DEV
      - TST
      - SND
      - PRE
      - PRD



resources:
  repositories:
    - repository: PipelineCommon
      name: DEFRA-TRD/Defra.TRD.Pipeline.Common
      type: git
      #ref: master
      ref: AJ/pts-node-js
variables:
  APIName: Defra.PTS.Dynamics.Functions

extends:
  template: /templates/basic-npm-webapp-deploy-pipeline.yaml@PipelineCommon
  parameters:
    forceDevDeploy: ${{ parameters.forceDevDeploy }}
    deployToSecondary: ${{ parameters.deployToSecondary}}
    appName: $(APIName)
    appProject: PTS
    appInstanceNumber: $(nc-region-id)04
    appSettingsEnv: 
      dev: >-
        -PORT "4002"
        -HOST "0.0.0.0"
    