name: "V1-B$(Date:yyyyMMdd)-$(BuildID)"

parameters:
  - name: forceDevDeploy
    displayName: "Deploy to DEV?"
    type: boolean
    default: false
  - name: deployToSecondary
    displayName: "Select Secondary Region"
    type: string
    default: None
    values:
      - None
      - DEV
      - TST
      - SND
      - PRE
      - PRD

resources:
  repositories:
    - repository: PipelineCommon
      name: DEFRA-TRD/Defra.TRD.Pipeline.Common
      type: git
      ref: master

variables:
  APIName: DEFRA_nipts-pts-checker-web-ui

extends:
  template: /templates/basic-npm-webapp-deploy-pipeline.yaml@PipelineCommon
  parameters:
    forceDevDeploy: ${{ parameters.forceDevDeploy }}
    deployToSecondary: ${{ parameters.deployToSecondary}}
    appProject: PTS
    appInstanceNumber: $(nc-region-id)04
    appName: DEFRA_nipts-pts-checker-web-ui
    appSettingsEnv:
      dev: >-
        -PORT "8080"
        -HOST "0.0.0.0"
        -BASE_API_URL "https://$(internalAPIMUrl)/pts-pet-checker/v1/api"
        -OCP_APIM_SUBSCRIPTION_KEY "3e9a5ea1359347869b60ee03d857cdac"
        -ACCOUNT_MANAGEMENT_URL "https://your-account.cpdev.cui.defra.gov.uk/management/account-management"
        -NODE_ENV  "development"
        -DEFRA_ID_REDIRECT_URI "https://$(environment)-check-a-pet-from-gb-to-ni.azure.defra.cloud/signin-oidc"
        -DEFRA_ID_SIGNOUT_URI "https://your-account.cpdev.cui.defra.gov.uk/idphub/b2c/b2c_1a_cui_cpdev_signupsignin/signout"
        -DEFRA_KEYVAULT_NAME "$(environment)trd$(nc-function-infrastructure-lower)$(nc-resource-keyvault-lower)1001"
      tst: >-
        -PORT "8080"
        -HOST "0.0.0.0"
        -BASE_API_URL "https://$(internalAPIMUrl)/pts-pet-checker/v1/api"
        -OCP_APIM_SUBSCRIPTION_KEY "285f8ed3d3e740df866e672d0e018072"
        -ACCOUNT_MANAGEMENT_URL "https://your-account.cpdev.cui.defra.gov.uk/management/account-management"
        -NODE_ENV  "test"
        -DEFRA_ID_REDIRECT_URI "https://$(environment)-check-a-pet-from-gb-to-ni.azure.defra.cloud/signin-oidc"
        -DEFRA_ID_SIGNOUT_URI "https://your-account.cpdev.cui.defra.gov.uk/idphub/b2c/b2c_1a_cui_cpdev_signupsignin/signout"
        -DEFRA_KEYVAULT_NAME "$(environment)trd$(nc-function-infrastructure-lower)$(nc-resource-keyvault-lower)1001"
      snd: >-
        -PORT "8080"
        -HOST "0.0.0.0"
        -BASE_API_URL "https://$(internalAPIMUrl)/pts-pet-checker/v1/api"
        -OCP_APIM_SUBSCRIPTION_KEY "TBC"
        -ACCOUNT_MANAGEMENT_URL "https://your-account.cp$(environment).cui.defra.gov.uk/management/account-management"
        -NODE_ENV  "send"
        -DEFRA_ID_REDIRECT_URI "https://$(environment)-check-a-pet-from-gb-to-ni.azure.defra.cloud/signin-oidc"
        -DEFRA_ID_SIGNOUT_URI "https://your-account.cpdev.cui.defra.gov.uk/idphub/b2c/b2c_1a_cui_cpdev_signupsignin/signout"
        -DEFRA_KEYVAULT_NAME "$(environment)trd$(nc-function-infrastructure-lower)$(nc-resource-keyvault-lower)1001"
      pre: >-
        -PORT "8080"
        -HOST "0.0.0.0"
        -BASE_API_URL "https://$(internalAPIMUrl)/pts-pet-checker/v1/api"
        -OCP_APIM_SUBSCRIPTION_KEY "TBC"
        -ACCOUNT_MANAGEMENT_URL "https://your-account.cp$(environment).cui.defra.gov.uk/management/account-management"
        -NODE_ENV  "preproduction"
        -DEFRA_ID_REDIRECT_URI "https://$(environment)-check-a-pet-from-gb-to-ni.azure.defra.cloud/signin-oidc"
        -DEFRA_ID_SIGNOUT_URI "TBC"
        -DEFRA_KEYVAULT_NAME "$(environment)trd$(nc-function-infrastructure-lower)$(nc-resource-keyvault-lower)1001"
      prd: >-
        -PORT "8080"
        -HOST "0.0.0.0"
        -BASE_API_URL "https://$(internalAPIMUrl)/pts-pet-checker/v1/api"
        -OCP_APIM_SUBSCRIPTION_KEY "TBC"
        -ACCOUNT_MANAGEMENT_URL "https://your-account.cp$(environment).cui.defra.gov.uk/management/account-management"
        -NODE_ENV  "production"
        -DEFRA_ID_REDIRECT_URI "https://$(environment)-check-a-pet-from-gb-to-ni.azure.defra.cloud/signin-oidc"
        -DEFRA_ID_SIGNOUT_URI "TBC"
        -DEFRA_KEYVAULT_NAME "$(environment)trd$(nc-function-infrastructure-lower)$(nc-resource-keyvault-lower)1001"
    runSonarScan: true
    #runVulnerabilityScan: true
    #skipOwaspScan: false
