const KeyVaultConstants = Object.freeze({
  DEFRA_ID_TENANT: "PTS-CP-B2C-TENANT",
  DEFRA_ID_POLICY: "PTS-CP-B2C-POLICY",
  DEFRA_ID_CLIENT_ID: "PTS-CP-B2C-CLIENT-ID",
  DEFRA_ID_CLIENT_SECRET: "PTS-CP-B2C-CLIENT-SECRET",
  DEFRA_ID_SERVICE_ID: "PTS-CP-B2C-SERVICE-ID",
  OCP_APIM_SUBSCRIPTION_KEY: "PTS-CP-OCP-APIM-SUBSCRIPTION-KEY",
});

export default KeyVaultConstants;
